export enum ActionType {
  APP_LOADED,
  SAVE_USER_DATA_STEP_1,
  SAVE_USER_DATA_AFTER_VERIFY,
  SAVE_USER_DATA_STEP_2,
  SAVE_USER_DATA_STEP_3,
  SAVE_LOGIN_DATA,
  LOGOUT,
  SAVE_NOTIFICATIONS,
  REMOVE_NOTIFICATIONS,
  SAVE_REGISTER_ERORRS,
  SAVE_LOGIN_ERORRS,
  SAVE_FORGET_PASSWORD_ERORRS,
  SAVE_PHONE
}
