export default {
  Login: 'تسجيل الدخول',
  Register: 'تسجيل جديد',
  'Forgot Password?': 'نسيت كلمة المرور؟',
  Profile: 'حسابي',
  Save: 'حفظ',
  Reset: 'إعادة تعيين',
  Logout: 'تسجل الخروج',
  Home: 'الرئيسية',
  Password: 'كلمة المرور',
  Phone: 'رقم الجوال',
  Email: 'البريد الإلكتروني',
  'Email "optional"': 'البريد الإلكتروني "اختياري"',
  'First name': 'الاسم الاول',
  'Last name': 'الاسم الاخير',
  'City': 'المدينة',
  'More': 'المزيد',
  'Riyadh': 'الرياض',
  'Password change': 'تعديل كلمة المرور',
  'Old password': 'كلمة المرور القديمة',
  'Your registration with us means your consent to': 'تسجيلك لدينا يعني موافقتك على',
  'Terms and Conditions': 'الشروط والأحكام',
  Send: 'إرسال',
  "Password Reset": 'إعادة تعيين كلمة المرور',
  "New bank account": 'حساب بنكي جديد',
  "Your confirmation of the order means your approval": 'تأكيدك للطلب يعني موافقتك على',
  "Search by order number": 'البحث برقم الطلب',
  "Confirmation": 'تأكيد الطلب',
  "Language": 'اللغة',
  "Rate us": 'تقييم التطبيق',
  "Share the app": 'مشاركة التطبيق',
  "Privacy policy": 'سياسة الخصوصية',
  "FAQ": 'الأسئلة الشائعة',
  "Faq": 'الأسئلة الشائعة',
  "Bank accounts": 'الحسابات البنكية',
  "About": 'عن التطبيق',
  "Skip": 'تخطي',
  "We provide brokerage services": "نقدم خدمات الوساطة المالية",
  "Facilitate and ensure buying and selling": "تسهيل وضمان البيع والشراء",
  "Building trust between clients": "بناء الثقة بين العملاء",
  "Mediation between the two parties until the purchase is confirmed in full": "الوساطة بين الطرفين لحين تأكيد عملية الشراء كاملة",
  "An intermediate electronic platform between both the seller and the buyer": "منصة إلكترونية وسيطة بين كلاً من البائع والمشتري",
  "Build trust among customers to complete and expand their purchases": "بناء الثقة بين العملاء لإتمام عمليات الشراء وتوسعها بشكل أكبر",
  "New password": 'كلمة المرور الجديدة',
  "GET STARTED": 'ابدأ الآن',
  "New password confirmation": 'تأكيد كلمة المرور الجديدة',
  "Password confirmation": 'تأكيد كلمة المرور',
  "Enter the activation code": 'ادخل كود التفعيل',
  "Activation code": 'كود التفعيل',
  "There are no bank accounts": 'لا يوجد حسابات بنكية',
  'Remaining': 'الوقت المتبقي',
  'Purchase order': 'طلب شراء',
  'Purchase': 'طلب شراء',
  'The cost of the order': 'التكلفة الخاصة بالطلب',
  'Sale order': 'طلب بيع',
  'Sale': 'طلب بيع',
  "The seller's name": 'اسم البائع',
  "Buyer's name": 'اسم المشتري',
  "The seller's mobile number": 'رقم الجوال الخاص بالبائع',
  "Buyer's mobile number": 'رقم الجوال الخاص بالمشتري',
  "Description of the purchase process": 'وصف عملية الشراء',
  "Description of the sales process": 'وصف عملية البيع',
  "Application percentage of 5% sale, select Parties to whom the percentage will be deducted": "نسبة التطبيق 5% من إجمالي عملية البيع،  حدد الأطراف التي ستخصم منهم  النسبة",
  'Confirmation of the order means your agreement to': 'تأكيدك للطلب يعني موافقتك على',
  'RESEND OPT': 'اعادة ارسال الكود',
  "Don't Receive The OPT ?": "لم تتلقى كود التفعيل ؟",
  "You can now log in to your account and start using Tajwrey services": "يمكنك الآن تسجيل الدخول إلى حسابكم والبدء بإستخدام خدمات تجوري",
  "Verify And Proceed": "تأكيد",
  "The first party requesting the request": "الطرف الأول صاحب الطلب",
  "The two parties together": "الطرفين معاً",
  "Second Party": "الطرف الثاني",
  "Username": "اسم المستخدم",
  "Order type": "حالة الطلب",
  "Notifications": "الإشعارات",
  "Contact us": "اتصل بنا",
  "All rights reserved © Tajwrey Corporation": "جميع الحقوق محفوظة © مؤسسة تجوري ",
  "Send us your inquiry": "ارسل لنا استفسارك",
  "Full name": "الاسم بالكامل",
  "Message": "الرسالة",
  "Please select language": "من فضلك اختر لغة",
  "English": "الانجليزية",
  "Arabic": "العربية",
  "Follow us on social media": "تابعنا على مواقع التواصل",
  "Confirm the payment": "تأكيد الدفع",
  "Edit profile": "تعديل بيانات الحساب",
  "The purchase order has been confirmed by the first party, confirm the payment to finish the process": "تم تأكيد طلب الشراء من قبل الطرف الأول، قم بتأكيد الدفع لإنهاء العملية",
  "Your account has been successfully registered": "تم تسجيل حسابكم بنجاح",
  "Enter your mobile number and a text message will be sent to activate and reset the password": "ادخل رقم جوالك وسيتم إرسال رسالة نصية للتفعيل وإعادة تعيين كلمة المرور",
  "Application percentage of 5% of total purchase, select Parties to whom the percentage will be deducted": "نسبة التطبيق 5% من إجمالي عملية البيع،  حدد الأطراف التي ستخصم منهم  النسبة",
  "Banks": "الحسابات البنكية",
  IBAN: 'الايبان',
  'Account number': 'رقم الحساب',
  'Account owner': 'اسم صاحب الحساب',
  'Bank name': 'اسم البنك',
  "Cancel": 'الغاء',
  "OK": 'نعم',
  "Do you want to delete the bank account?": "هل تريد حذف الحساب البنكي؟",

};
