export default {
  Login: 'تسجيل الدخول',
  Register: 'تسجيل جديد',
  'Forgot Password?': 'نسيت كلمة المرور؟',
  Profile: 'الملف الشخصي',
  Save: 'حفظ',
  Reset: 'إعادة تعيين',
  Logout: 'تسجل الخروج',
  Home: 'الرئيسية',
  Password: 'كلمة المرور',
  Phone: 'رقم الجوال',
  Email: 'البريد الإلكتروني',
  'Email "optional"': 'البريد الإلكتروني "اختياري"',
  'First name': 'الاسم الاول',
  'Last name': 'الاسم الاخير',
  'City': 'المدينة',
  'More': 'المزيد',
  'Riyadh': 'الرياض',
  'Password change': 'تعديل كلمة المرور',
  'Old password': 'كلمة المرور القديمة',
  'Your registration with us means your consent to': 'تسجيلك لدينا يعني موافقتك على',
  'Terms and Conditions': 'الشروط والأحكام',
  Send: 'إرسال',
  "Password Reset": 'إعادة تعيين كلمة المرور',
  "Search by order number": 'البحث برقم الطلب',
  "New password": 'كلمة المرور الجديدة',
  "New password confirmation": 'تأكيد كلمة المرور الجديدة',
  "Enter the activation code": 'ادخل كود التفعيل',
  'Remaining': 'الوقت المتبقي',
  'Purchase order': 'طلب شراء',
  'The cost of the order': 'التكلفة الخاصة بالطلب',
  'Sale order': 'طلب بيع',
  "The seller's name": 'اسم البائع',
  "Buyer's name": 'اسم المشتري',
  "The seller's mobile number": 'رقم الجوال الخاص بالبائع',
  "Buyer's mobile number": 'رقم الجوال الخاص بالمشتري',
  "Description of the purchase process": 'وصف عملية الشراء',
  "Description of the sales process": 'وصف عملية البيع',
  "Application percentage of 5% sale, select Parties to whom the percentage will be deducted": "نسبة التطبيق 5% من إجمالي عملية البيع،  حدد الأطراف التي ستخصم منهم  النسبة",
  'Confirmation of the order means your agreement to': 'تأكيدك للطلب يعني موافقتك على',
  'RESEND OPT': 'اعادة ارسال الكود',
  "Don't Receive The OPT ?": "لم تتلقى كود التفعيل ؟",
  "Verify And Proceed": "تأكيد",
  "The first party requesting the request": "الطرف الأول صاحب الطلب",
  "The two parties together": "الطرفين معاً",
  "Second Party": "الطرف الثاني",
  "Username": "اسم المستخدم",
  "Order type": "حالة الطلب",
  "Notifications": "الإشعارات",
  "Contact us": "اتصل بنا",
  "Send us your inquiry": "ارسل لنا استفسارك",
  "Full name": "الاسم بالكامل",
  "Message": "الرسالة",
  "Please select language": "من فضلك اختر لغة",
  "English": "الانجليزية",
  "Arabic": "العربية",
  "Follow us on social media": "تابعنا على مواقع التواصل",
  "Confirm the payment": "تأكيد الدفع",
  "Edit profile": "تعديل بيانات الحساب",
  "The purchase order has been confirmed by the first party, confirm the payment to finish the process": "تم تأكيد طلب الشراء من قبل الطرف الأول، قم بتأكيد الدفع لإنهاء العملية",
  "Your account has been successfully registered": "تم تسجيل حسابكم بنجاح",
  "Enter your mobile number and a text message will be sent to activate and reset the password": "ادخل رقم جوالك وسيتم إرسال رسالة نصية للتفعيل وإعادة تعيين كلمة المرور",
  "Application percentage of 5% of total purchase, select Parties to whom the percentage will be deducted": "نسبة التطبيق 5% من إجمالي عملية البيع،  حدد الأطراف التي ستخصم منهم  النسبة",
  "Banks": "الحسابات البنكية",
  IBAN: 'الايبان',
  'Account number': 'رقم الحساب',
  'Account owner': 'اسم صاحب الحساب',
  'Bank name': 'اسم البنك',

};
